import { Document, Page, View, Text, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { formatCurrency, formatDate } from "@/lib/utils";
import type { InvoiceData } from "@/lib/invoice-data";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#1a1a1a" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  orgName: { fontSize: 16, fontWeight: "bold" },
  invoiceTitle: { fontSize: 20, fontWeight: "bold", textAlign: "right" },
  invoiceMeta: { fontSize: 10, textAlign: "right", color: "#555555", marginTop: 4 },
  section: { marginBottom: 16 },
  label: { fontSize: 8, color: "#888888", marginBottom: 2 },
  addressLine: { fontSize: 10, marginBottom: 1 },
  table: { marginTop: 12, borderTopWidth: 1, borderTopColor: "#dddddd" },
  tableHeaderRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#dddddd", paddingVertical: 6 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#eeeeee", paddingVertical: 8 },
  colDescription: { flexGrow: 3 },
  colAmount: { flexGrow: 1, textAlign: "right" },
  totalRow: { flexDirection: "row", justifyContent: "flex-end", marginTop: 12 },
  totalLabel: { fontSize: 11, fontWeight: "bold", marginRight: 12 },
  totalAmount: { fontSize: 11, fontWeight: "bold" },
  statusLine: { fontSize: 9, color: "#555555", marginTop: 4 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#999999", textAlign: "center" },
});

function InvoicePage({ invoice }: { invoice: InvoiceData }) {
  return (
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <View>
          <Text style={styles.orgName}>{invoice.organizationName}</Text>
        </View>
        <View>
          <Text style={styles.invoiceTitle}>INVOICE</Text>
          <Text style={styles.invoiceMeta}>{invoice.invoiceNumber}</Text>
          <Text style={styles.invoiceMeta}>{formatDate(invoice.issuedAt)}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.label}>BILLED TO</Text>
        <Text style={styles.addressLine}>{invoice.customerName}</Text>
        {invoice.billingAddressLines.map((line, i) => (
          <Text key={i} style={styles.addressLine}>
            {line}
          </Text>
        ))}
        {invoice.customerEmail && <Text style={styles.addressLine}>{invoice.customerEmail}</Text>}
      </View>

      {invoice.serviceAddressLines.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.label}>SERVICE ADDRESS</Text>
          {invoice.serviceAddressLines.map((line, i) => (
            <Text key={i} style={styles.addressLine}>
              {line}
            </Text>
          ))}
        </View>
      )}

      <View style={styles.table}>
        <View style={styles.tableHeaderRow}>
          <Text style={[styles.colDescription, styles.label]}>DESCRIPTION</Text>
          <Text style={[styles.colAmount, styles.label]}>AMOUNT</Text>
        </View>
        <View style={styles.tableRow}>
          <Text style={styles.colDescription}>{invoice.serviceDescription}</Text>
          <Text style={styles.colAmount}>{formatCurrency(invoice.amount, invoice.currency)}</Text>
        </View>
      </View>

      <View style={styles.totalRow}>
        <Text style={styles.totalLabel}>Total</Text>
        <Text style={styles.totalAmount}>{formatCurrency(invoice.amount, invoice.currency)}</Text>
      </View>
      <Text style={styles.statusLine}>Status: {invoice.status.replace(/_/g, " ")}</Text>

      <Text style={styles.footer} fixed>
        {invoice.organizationName} · Generated by RoundFlow
      </Text>
    </Page>
  );
}

export function InvoicesPdfDocument({ invoices }: { invoices: InvoiceData[] }) {
  return (
    <Document>
      {invoices.map((invoice) => (
        <InvoicePage key={invoice.invoiceNumber} invoice={invoice} />
      ))}
    </Document>
  );
}

/** Renders one or more invoices into a single PDF — one page per invoice. */
export async function renderInvoicesPdf(invoices: InvoiceData[]): Promise<Buffer> {
  return renderToBuffer(<InvoicesPdfDocument invoices={invoices} />);
}
