import { prisma } from "@/lib/prisma";
import { normalizeAreaName, colorForArea } from "@/lib/utils";

export const AUTO_ROUND_MARKER = "Auto-generated round for";

/**
 * Finds or creates the round for a given area name, normalizing casing so
 * "preston", "Preston", and "PRESTON" all resolve to one round rather than
 * silently creating duplicates.
 */
export async function upsertAreaRound(organizationId: string, cityRaw: string) {
  const areaName = normalizeAreaName(cityRaw);
  return prisma.round.upsert({
    where: { organizationId_name: { organizationId, name: areaName } },
    update: {},
    create: {
      organizationId,
      name: areaName,
      description: `${AUTO_ROUND_MARKER} ${areaName}`,
      colorCode: colorForArea(areaName),
    },
  });
}

/**
 * Moves every job for a property onto the given round (used when a
 * property's city is corrected after the fact) and cleans up any
 * now-empty auto-generated round left behind, so a typo fix doesn't
 * leave an orphaned duplicate round sitting on the Rounds page.
 */
export async function reassignPropertyJobsToRound(propertyId: string, roundId: string) {
  const affectedRounds = await prisma.job.findMany({
    where: { propertyId },
    select: { roundId: true },
    distinct: ["roundId"],
  });

  await prisma.job.updateMany({
    where: { propertyId },
    data: { roundId },
  });

  for (const { roundId: oldRoundId } of affectedRounds) {
    if (oldRoundId === roundId) continue;
    await deleteRoundIfEmptyAndAutoGenerated(oldRoundId);
  }
}

async function deleteRoundIfEmptyAndAutoGenerated(roundId: string) {
  const remaining = await prisma.job.count({ where: { roundId } });
  if (remaining > 0) return;

  const round = await prisma.round.findUnique({ where: { id: roundId } });
  if (round?.description?.startsWith(AUTO_ROUND_MARKER)) {
    await prisma.round.delete({ where: { id: roundId } });
  }
}
