import { prisma } from "@/lib/prisma";
import { normalizeAreaName, colorForArea, startOfDay, endOfDay } from "@/lib/utils";

export const AUTO_ROUND_MARKER = "Auto-generated round for";

/**
 * Finds or creates the round for a given area name, normalizing casing so
 * "preston", "Preston", and "PRESTON" all resolve to one round rather than
 * silently creating duplicates.
 */
export async function upsertAreaRound(organizationId: string, cityRaw: string) {
  const areaName = normalizeAreaName(cityRaw);
  return prisma.round.upsert({
    where: { organizationId_name: { organizationId, name: areaName } },
    update: {},
    create: {
      organizationId,
      name: areaName,
      description: `${AUTO_ROUND_MARKER} ${areaName}`,
      colorCode: colorForArea(areaName),
    },
  });
}

/**
 * Sets a property's round (the source of truth going forward, rather than
 * re-deriving it from the city every time) and moves every one of its
 * existing jobs onto that round too. Used both for the automatic
 * city-based assignment and for manually moving a property to a different
 * round — e.g. once a big area round like "Preston" needs splitting into
 * day-sized sub-rounds. Cleans up a now-empty auto-generated round left
 * behind so a reassignment doesn't leave an orphaned duplicate.
 *
 * `locked: true` marks the assignment as manual, so future automatic
 * city-based reassignment (on an address edit) leaves it alone.
 */
export async function assignPropertyToRound(
  propertyId: string,
  roundId: string,
  options?: { locked?: boolean }
) {
  const affectedRounds = await prisma.job.findMany({
    where: { propertyId },
    select: { roundId: true },
    distinct: ["roundId"],
  });

  await prisma.property.update({
    where: { id: propertyId },
    data: {
      roundId,
      ...(options?.locked ? { roundLocked: true } : {}),
    },
  });

  await prisma.job.updateMany({
    where: { propertyId },
    data: { roundId },
  });

  for (const { roundId: oldRoundId } of affectedRounds) {
    if (oldRoundId === roundId) continue;
    await deleteRoundIfEmptyAndAutoGenerated(oldRoundId);
  }
}

/**
 * One crew covers one area per day, so two different rounds can never
 * both have work booked on the same date. Returns the other round already
 * occupying that date, or null if the date is free (or only has jobs on
 * the same round already).
 */
export async function findConflictingRound(params: {
  organizationId: string;
  date: Date;
  roundId: string;
}): Promise<{ id: string; name: string } | null> {
  const conflictingJob = await prisma.job.findFirst({
    where: {
      organizationId: params.organizationId,
      scheduledDate: { gte: startOfDay(params.date), lte: endOfDay(params.date) },
      roundId: { not: params.roundId },
      status: { in: ["SCHEDULED", "IN_PROGRESS", "COMPLETED"] },
    },
    include: { round: true },
  });

  return conflictingJob ? { id: conflictingJob.round.id, name: conflictingJob.round.name } : null;
}

async function deleteRoundIfEmptyAndAutoGenerated(roundId: string) {
  const remaining = await prisma.job.count({ where: { roundId } });
  if (remaining > 0) return;

  const round = await prisma.round.findUnique({ where: { id: roundId } });
  if (round?.description?.startsWith(AUTO_ROUND_MARKER)) {
    await prisma.round.delete({ where: { id: roundId } });
  }
}
